### ISSUE TITLE
YouTube videos do not autoplay if the tab does not have focus (Chrome)

### ISSUE THREAD

**Issue by Fauntleroy** [Fauntleroy/tandem.io#105]
If tandem.io isn't currently focused, YouTube videos will fail to play automatically. This happens because of a combination of a few issues:

- YouTube players come from iframes
- In Google chrome, video autoplay behavior has been changed. Videos can only autoplay if the tab has had focus
- Since [`react-player`](https://github.com/CookPete/react-player) destroys the `iframe` every time a new video is loaded, the tab needs to attain focus again for the YouTube iframe to have permission to autoplay

`react-player` has recently been updated to potentially fix the issue. It needs to be tested out and verified.

**Comment by svincent** [comment]
Test case via @Fauntleroy over Slack:

> I should probably provide a method for replication
>
> 1. Open two windows in the same room
> 2. Make sure one is defocused but not muted
> 3. Add a YouTube video in the other window
> 4. Both the active and defocused windows should play

**Comment by Fauntleroy** [comment]
So I've updated to the latest version of `react-player` and pushed it to production (http://www.tandem.io/). Some brief testing has verified that this particular issue is resolved. Please go through the test case in production and verify that things are working on your end. YouTube videos and Soundcloud tracks should always play automatically in all circumstances.

**Comment by svincent** [comment]
I verified videos are synced using Chrome and Firefox. Apologies for getting sidetracked in drink and gifs.

**Comment by Fauntleroy** [comment]
Looks like we just rectified the minification issue as well: https://github.com/CookPete/react-player/issues/17
