### ISSUE TITLE
Volume is improperly set on first load

### ISSUE THREAD

**Issue by Fauntleroy** [Fauntleroy/tandem.io#110]
If the user has set the volume the player will not initialize with the correct volume on the first load. When another player is loaded, the volume is properly set.

My suspicion is that the volume is not being passed around `react-player` properly internally before the YouTube SDK is loaded.

**Comment by Fauntleroy** [comment]
https://github.com/CookPete/react-player/issues/23

**Comment by CookPete** [comment]
This should be fixed in `react-player@0.3.5`

**Comment by Fauntleroy** [comment]
Resolved by updating to `0.3.7` https://github.com/Fauntleroy/tandem.io/commit/a8c2df93242e059e63dfd171e0a336ed0a400233
